spring:
  profiles:
    active: local
  datasource:
    driverClassName: org.postgres.Driver
    url: postgresql://localhost:5432/RPG
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect      
          
          